export const Routes = {
  Login: 'Login',
  SignUp: 'Sign Up',
  Home: 'Home',
  ForgetPassword: 'Forget Password',
  LoggedInScreen: 'LoggedIn Screen',
  Menu: 'Menu',
  Settings: 'Settings',
  ProfileSettings: 'Profile Settings',
  EditField: 'Edit Field',
  ChangePassword: 'Change Password',
  SuccessChangePassword: 'Success Change Password',
  DeleteAccount: 'Delete Account',
  DeleteAccountSecondStep: 'Delete Account second step',
  DeleteAccountThirdStep: 'Delete Account third step',
};
