name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run Jest Tests with Coverage
        run: npm run test:coverage

      - name: Check for lcov.info in the root directory
        run: ls -R  # List all files to confirm lcov.info is in the root

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: lcov.info  # Upload lcov.info directly from the root

  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    needs: run-tests

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar

      - name: Download coverage artifact
        uses: actions/download-artifact@v4
        with:
          name: coverage-report

      - name: Check downloaded directory
        run: ls -R  # List all files to verify lcov.info is downloaded to the root

      - name: Display lcov.info content
        run: cat lcov.info || echo "lcov.info not found"

      - name: Run SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.organization=${{ secrets.SONAR_ORG }}
            -Dsonar.sources=.
            -Dsonar.exclusions=node_modules/**,android/**,ios/**,**/*.test.js,__tests__/**,app/**/*.html,!coverage/index.html
            -Dsonar.javascript.lcov.reportPaths=lcov.info  # Point directly to lcov.info in the root
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
